repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: validate
        name: Validate
        entry: pnpm run validate
        language: system
        pass_filenames: false
        always_run: true
