version: '3'
services:
  prod:
    build: .
    environment:
      - HOST=0.0.0.0
      - SESSION_SECRET
    ports:
      - 3000:3000
      - 5555:5555
  dev:
    image: node:20.10.0
    environment:
      - HOST=0.0.0.0
      - SESSION_SECRET
    ports:
      - 3000:3000
      - 3001:3001
      - 5555:5555
      - 8080:8080 # remix DevTools websocket server
    volumes:
      - .:/geb1024com
      - node_modules:/geb1024com/node_modules
    working_dir: /geb1024com
    command: bash
  validate:
    image: mcr.microsoft.com/playwright:v1.40.1-jammy
    environment:
      - HOST=0.0.0.0
      - SESSION_SECRET
    volumes:
      - .:/geb1024com
      - node_modules:/geb1024com/node_modules
    ports:
      - 3000:3000
      - 3001:3001
      - 5555:5555
      - 8080:8080 # remix DevTools websocket server
      - 9323:9323 # playwright reporter
    working_dir: /geb1024com
    command: npm run validate
volumes:
  node_modules:
