version: '3'
services:
  prod:
    build: .
    environment:
      - HOST=0.0.0.0
      - DATABASE_URL
      - SESSION_SECRET
      - APP_URL
    ports:
      - 3000:3000
      - 5555:5555
  dev:
    image: node:20.10.0
    environment:
      - HOST=0.0.0.0
      - DATABASE_URL
      - SESSION_SECRET
      - APP_URL
    ports:
      - 3000:3000
      - 3001:3001
      - 5555:5555
      - 8080:8080 # remix DevTools websocket server
    volumes:
      - .:/8bit-stack
      - node_modules:/8bit-stack/node_modules
    working_dir: /8bit-stack
    command: bash
  validate:
    image: mcr.microsoft.com/playwright:v1.40.1-jammy
    environment:
      - HOST=0.0.0.0
      - DATABASE_URL
      - SESSION_SECRET
      - APP_URL
    volumes:
      - .:/8bit-stack
      - node_modules:/8bit-stack/node_modules
    ports:
      - 3000:3000
      - 3001:3001
      - 5555:5555
      - 8080:8080 # remix DevTools websocket server
      - 9323:9323 # playwright reporter
    working_dir: /8bit-stack
    command: npm run validate
volumes:
  node_modules:
