// This file is auto-generated by update-knowledge-piece-list.ts

// should not import using path alias "~" as it won't be resolved when parsing react-router.config.ts on typegen, build, etc.
import piece0 from "../../contents/knowledge-pieces/how-js-framework-works/content";
import piece1 from "../../contents/knowledge-pieces/spa-ssr/content";
import piece2 from "../../contents/knowledge-pieces/webstd1-what-is/content";
import piece3 from "../../contents/knowledge-pieces/webstd2-who-creates/content";
import piece4 from "../../contents/knowledge-pieces/webstd3-tools-align-standard/content";
import piece5 from "../../contents/knowledge-pieces/webstd4-ex-specs/content";

export function getAllKnowledgePieces() {
  return [piece0, piece1, piece2, piece3, piece4, piece5].filter((p) => {
    const now = new Date();
    now.setHours(0, 0, 0, 0);
    return p.date < new Date(now.getFullYear(), now.getMonth(), now.getDate() + 1);
  });
}
