// This file is auto-generated by update-knowledge-piece-list.ts
import piece0 from "../../contents/knowledge-pieces/how-js-framework-works/content";
import piece1 from "../../contents/knowledge-pieces/spa-ssr/content";

export function getAllKnowledgePieces() {
  return [piece0, piece1];
}
